---
#- name: Install MySQL
#  hosts: db_server
#  become: yes
#  roles:
#    - setup_mysql

- name: Install Apache2
  hosts: http_server
  become: yes
  roles:
    - setup_apache
    - setup_php
    - setup_wordpress