---
# tasks file for setup_mysql
- name: Install MySQL
  apt: name="{{ item }}" update_cache=yes state=present
  loop: [ 'mysql-server', 'python3-pymysql' ]
  
- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create database
  mysql_db:
    name: "wordpress"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create user
  mysql_user:
    name: "wordpress"
    host: "{{ http_host }}"
    password: "{{ mysql_password }}"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Change mysqld.conf
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    replace: "#bind-address"
    
- name: Restart MySQL service
  service:
    name: mysql
    state: restarted  
    enabled: yes