---
# tasks file for setup_apache
- name: Insatll apache2
  apt:
    name: apache2
    update_cache: yes
    state: present
    
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    mode: '0755'

- name: Copy Apache config
  template:
    src: "templates/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache

- name: Enable site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Restart Apache

- name: Disable default site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Reload Apache

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp